import { Injectable } from '@angular/core';
import { Recipe } from '../../recipes/models/recipe.interface';

@Injectable({
  providedIn: 'root'
})
export class RecipeFormatterService {

  constructor() { }

  formatRecipeToText(recipe: Recipe): string {
    const separator = '─'.repeat(50);
    
    return `
🍳 ${recipe.name.toUpperCase()}
${separator}

📝 DESCRIPTION:
${recipe.description}

🥩 PROTEIN:
${recipe.protein}

🛒 INGREDIENTS:
${recipe.ingredients.map((ingredient, index) => `${index + 1}. ${ingredient}`).join('\n')}

💡 NOTES & STORAGE TIPS:
${recipe.notes}

${separator}
Generated by Recipe Assistant
${new Date().toLocaleDateString('en-US', {
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'numeric'
})}
    `.trim();
  }
}
